version: "3"
services:
  web:
    build:
      context: ./cartogram-web/
      dockerfile: Dockerfile
    image: gocart-web
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    environment:
      - CARTOGRAM_PORT=5001
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:{}@postgres/cartogram
      - POSTGRES_PASSWORD_FILE=/run/secrets/password
    command: sh -c "python -c \"import web; web.db.create_all()\" && ./gunicorn.sh"
    ports:
      - "5001:5001"
    volumes:
      - ./data/userdata:/root/internal/static/userdata
    secrets:
      - password
    dns:
      - 8.8.8.8

  exp:
    build:
      context: ./cartogram-web/
      dockerfile: Dockerfile
    image: gocart-web
    profiles: [exp]
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    environment:
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:{}@postgres/cartogramexp
      - POSTGRES_PASSWORD_FILE=/run/secrets/password
      - CARTOGRAM_PORT=5000
      - VITE_SERVER_PORT=5174
      - CARTOGRAM_GUNICORN_WORKERS=1
    command: sh -c "python -c \"import web; web.db.create_all()\" && ./gunicorn.sh"
    ports:
      - "5000:5000"
    volumes:
      - ./cartogram-exp/internal:/root/internal
      - ./cartogram-exp/data:/root/data
    secrets:
      - password
    dns:
      - 8.8.8.8

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=cartogram
      - POSTGRES_PASSWORD_FILE=/run/secrets/password
      - POSTGRES_MULTIPLE_DATABASES=cartogramexp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    secrets:
      - password

secrets:
  password:
    file: password.txt
