version: '3'
services:
  web:
    image: janskyd/cartogram-web
    env_file:
      - ./web-production.env
    depends_on:
      - redis
      - postgres
    environment:
      - CARTOGRAM_DEBUG=FALSE
      - CARTOGRAM_HOST=0.0.0.0
      - CARTOGRAM_PORT=5000
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:cartogram@postgres/cartogram
      - CARTOGRAM_USE_DATABASE=TRUE
      - CARTOGRAM_REDIS_HOST=redis
      - CARTOGRAM_REDIS_PORT=6379
    ports:
      - '5000:5000'
    dns:
      - 8.8.8.8
    restart: always
  redis:
    image: redis
    restart: always
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=cartogram
      - POSTGRES_USER=cartogram
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
