name: Deploy

jobs:
  if: github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  steps:
    - name: Deploy
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: ./deploy.sh
